# Generated by Django 5.1.2 on 2024-10-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_rename_ip_address_location_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lan',
            field=models.CharField(default=545545454, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.CharField(default=5645645, max_length=45),
            preserve_default=False,
        ),
    ]
